# Sanity check
ifeq ($(wildcard $(HITD_HOME)/src/nemu/nemu-main.cpp),)
  $(error HITD_HOME=$(HITD_HOME) is not a HITD repo)
endif

CPUS = $(shell expr $(shell nproc) / 2)

# Include variables and rules generated by menuconfig
-include $(HITD_HOME)/include/config/auto.conf
-include $(HITD_HOME)/include/config/auto.conf.cmd

remove_quote = $(patsubst "%",%,$(1))
GUEST_ISA ?= $(call remove_quote,$(CONFIG_ISA))

# Include rules for menuconfig
include $(HITD_HOME)/scripts/config.mk

# use verilator ar and cpp compile elf
include $(HITD_HOME)/scripts/cpp_to_elf.mk
